@startuml 診察記録
 left to right direction
class "医者" as doctor {
}
class "患者" as patient {
}
class "医局" as unit {
-外科
-内科
-小児科
}
class "診察記録" as check {
}

doctor "1" --> "1" patient :診察 > 
doctor "1" --> "*" unit :所属 >
doctor "1" --> "*" check :記録 >
@enduml